export const descriptionPlaceholder = `
<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; color: rgb(0, 0, 0); font-family: "Nanum Gothic"; font-size: 30px;'><strong style="box-sizing: border-box; font-weight: 700;">호스트 소개</strong></span></p>
<hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); clear: both; user-select: none; break-after: page; color: rgb(33, 37, 41); font-family: &quot;Noto Sans KR&quot;, Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; background-color: rgb(239, 239, 239); font-size: 14px; font-family: "Nanum Barun Gothic";'>아래 필수 질문에 대한 답변을 작성하신 다음에, 제목(호스트 소개)을 제외한 모든 글을 지워주세요 :)</span><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; font-size: 14px;"><br style="box-sizing: border-box;"></span></span><span style='box-sizing: border-box; background-color: rgb(239, 239, 239); font-size: 14px; font-family: "Nanum Barun Gothic";'>사진은 적절한 장수와 적절한 위치를 추천해 드립니다.&nbsp;</span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">**필수 질문 : 이름(닉네임)을 포함하여 1줄 소개를 부탁드려요.<br style="box-sizing: border-box;"></span></strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><strong style="box-sizing: border-box; font-weight: 700;">안녕하세요. 하고 싶은 일이 너무 많아 고민인 호스트 김영이입니다</strong><strong style="box-sizing: border-box; font-weight: 700;">.</strong><strong style="box-sizing: border-box; font-weight: 700;">&nbsp;</strong></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot;호스트님의 얼굴이나 실루엣이 나타난 사진이 좋습니다&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 현재 하는 일(공부)을 소개해주세요.<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">주중에는 IT 스타트업에서 기획업무를 맡고 있고요.&nbsp;</strong></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">주말에는 평일에 하지 못했던 이런저런 취미생활에 한껏 빠져있습니다.</strong></span><strong style="box-sizing: border-box; font-weight: 700;">&nbsp;</strong></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style='box-sizing: border-box; color: rgb(65, 65, 65); font-family: "Nanum Barun Gothic"; font-size: 14px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>&quot;호스트님의 일, 취미 등 삶을 나타내는 사진이 좋아요&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 최근에 관심이 많은 일을 알려주세요.<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">직업 특성상 많은 사람과 소통을 나누는 데 에너지를 소비하다 보니,</strong></span><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">주말에는 보통 힐링할 수 있는 활동들을 많이 찾고 있어요.</strong></span><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong></span><span style="box-sizing: border-box; color: rgb(124, 112, 107); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">집에서 이것저것 소소하게 만들어보기도 하고, 차 모임에 참석해서 마음의 여유를 되찾기도 합니다.</strong></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style='box-sizing: border-box; color: rgb(65, 65, 65); font-family: "Nanum Barun Gothic"; font-size: 14px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255);'><em style='box-sizing: border-box; color: rgb(65, 65, 65); font-family: "Nanum Barun Gothic"; font-size: 14px; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; background-color: rgb(255, 255, 255);'>&quot;호</em>스트님의 일, 취미 등 삶을 나타내는 사진이 좋아요&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 남의집 호스트가 된 계기가 궁금해요.<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong></span><span style="box-sizing: border-box; color: rgb(163, 143, 132);"><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong></span><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">그러다 우연히 &#39;남의집&#39;이라는 신기한 플랫폼을 알게 되어,&nbsp;</strong></span><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><br style="box-sizing: border-box;">이제는 나의 취향과 맞는 분들을 집으로 초대하여 서로 힘이 되는 잔잔한 대화를 나누고 싶어서<br style="box-sizing: border-box;"></span></strong></span></span><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Barun Gothic"; color: rgb(124, 112, 107);'><strong style="box-sizing: border-box; font-weight: 700;">호스트가 되기로 결정했어요.</strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p>
	<br>
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br>
</p>
`;

export const favoritePlaceholder = `
<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; color: rgb(0, 0, 0); font-family: "Nanum Gothic"; font-size: 30px;'><strong style="box-sizing: border-box; font-weight: 700;">주제 소개</strong></span></p>
<hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); clear: both; user-select: none; break-after: page; color: rgb(33, 37, 41); font-family: &quot;Noto Sans KR&quot;, Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; background-color: rgb(239, 239, 239); color: rgb(0, 0, 0); font-size: 14px; font-family: "Nanum Barun Gothic";'>아래 필수 질문에 대한 답변을 작성하신 다음에, 제목(주제 소개)을 제외한 모든 글을 지워주세요 :)</span><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(0, 0, 0);"><br style="box-sizing: border-box; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"><span style="box-sizing: border-box; background-color: rgb(239, 239, 239);">사진은 적절한 장수와 적절한 위치를 추천해 드립니다.</span></span><span style="box-sizing: border-box; background-color: rgb(239, 239, 239); color: rgb(0, 0, 0);">&nbsp;</span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">**필수 질문 : 명확한 주제를 설명해주세요. 두 가지 이상의 주제를 버무려도 괜찮습니다.<br style="box-sizing: border-box;"></span></strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">어떤 주제로 남의집을 열까 잠시 고민했어요.&nbsp;</strong></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">그러다가 어렵지 않게 나를 가장 행복하게 만드는 주제를 떠올린 것 같아요.</strong></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">어쩌면 너무나 평범할 수 있지만, 이름만 들어도 설레는 &#39;여행&#39; 이죠.</strong></span></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot;주제와 관련된 사진을 넣어주세요.&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 선택한 주제의 매력 혹은 관심 갖게 된 이유는 무엇인가요?<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">친구들과 MT로 종종 가던 가평, 먹부림을 하고 싶어 떠났던 전주, 바다가 그리워 떠났던 부산, 다 너무 소중한 추억이었던 것 같아요. 가끔 그때 찍었던 사진들을 들춰보면 삭막한 일상에 잔잔한 여유를 던져주곤 합니다.</strong></span></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot;주제와 관련된 사진을 넣어주세요&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 주제와 관련해서 하는 활동 혹은 취미는 무엇인가요?<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">최근에는 국내를 기차 여행해보거나 유럽 일주를 해볼까 하는 작은 목표도 가지고 있어요.</strong></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style="box-sizing: border-box; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;"><strong style="box-sizing: border-box; font-weight: 700;">여행 관련 영상도 자기 전에는 꼭 하나씩은 보는 것 같아요.&nbsp;</strong></span></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot;주제와 관련된 사진을 넣어주세요&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 게스트를 초대했을 때 나누고 싶은 이야기는 무엇인가요?</span></strong><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);"><br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong></span><span style="box-sizing: border-box; color: rgb(163, 143, 132);"><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong></span></span><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic"; color: rgb(124, 112, 107);'><strong style="box-sizing: border-box; font-weight: 700;">요즘은 여행 다니시는 분들이 많아서, 서로의 여행 이야기를 나누는 것 자체가 힐링이고 간접경험이더라고요.</strong><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">제가 국내 여행의 소소한 매력도 알려드리고,</strong><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">저 또한 여행을 좋아하는 게스트분들에게 재미있는 이야기를 많이 듣고 싶네요 :)</strong></span></span></p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);"><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot;주제와 관련된 사진을 넣어주세요&quot;</em></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><br style="box-sizing: border-box;"></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);">**필수 질문 : 입장료에 포함된 제공사항은 무엇인가요?<br style="box-sizing: border-box;"></span></strong></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);">예시)<br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">사는 곳 근처에 자주 가는 동네 빵집이 있어요. 지나갈 때마다 구매 욕구를 불러일으키는 아주 향기 좋은 곳이랍니다.</strong><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">아침에 갓 구운 빵들을 사다가 마련해놓을게요. &nbsp;</strong><br style="box-sizing: border-box;"><strong style="box-sizing: border-box; font-weight: 700;">그리고 커피나, 커피를 못 마시는 분들에게는 주스 혹은 차를 대접해드릴게요 :)</strong><br style="box-sizing: border-box;"></span></span></span><strong style="box-sizing: border-box; font-weight: 700;"><span style='box-sizing: border-box; color: rgb(124, 112, 107); font-family: "Nanum Barun Gothic"; font-size: 14px;'>*주차는 공간이 협소하여 어렵습니다. 대중교통 이용 부탁드려요.</span></strong></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p>
	<br>
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br>
</p>`;

export const spaceIntroductionPlaceholder = `
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);"><span style='box-sizing: border-box; color: rgb(0, 0, 0); font-family: "Nanum Gothic"; font-size: 30px;'><strong style="box-sizing: border-box; font-weight: 700;">공간 소개</strong></span></p>
<hr style="box-sizing: content-box; height: 0px; overflow: visible; border: 0.5px solid rgb(238, 238, 238); clear: both; user-select: none; break-after: page; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; margin: 16px 0px; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);">

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);"><span style='box-sizing: border-box; background-color: rgb(239, 239, 239); color: rgb(0, 0, 0); font-size: 14px; font-family: "Nanum Barun Gothic";'>아래 필수 질문에 대한 답변을 작성하신 다음에, 제목(공간 소개)을 제외한 모든 글을 지워주세요 :)</span><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; font-size: 14px;"><span style="box-sizing: border-box; color: rgb(0, 0, 0);"><br style="box-sizing: border-box;"></span></span></span><span style='box-sizing: border-box; background-color: rgb(239, 239, 239); color: rgb(0, 0, 0); font-size: 14px; font-family: "Nanum Barun Gothic";'>사진은 적절한 장수와 적절한 위치를 추천해 드립니다.</span></p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);">
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">**필수 질문 : 공간에 대한 간략한 설명을 적어주세요 :)&nbsp;</span></strong></span>
	<br style="box-sizing: border-box;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">살고 있다거나, 직접 운영하는 공간이라는 멘트를 꼭 넣어 호스트의 개인 공간이라는 점을 알려주세요.<br style="box-sizing: border-box;"></span></strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style='box-sizing: border-box; color: rgb(124, 112, 107); font-family: "Nanum Gothic"; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;'><strong style="box-sizing: border-box; font-weight: 700;">서울 종로 인근에 조용한 동네에 위치한 연립주택이에요. 어느덧 이곳에 산 지 5년이 넘었네요</strong></span><span style='box-sizing: border-box; color: rgb(0, 0, 0); font-family: "Nanum Gothic"; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; float: none; display: inline !important;'>.</span></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(2~3장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot; 실제 공간 사진을 넣어주세요.&quot;</em></span></span></p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);">
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">**필수 질문 : 공간의 매력을 설명해주세요</span></strong><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">.<br style="box-sizing: border-box;"></span></strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><strong style="box-sizing: border-box; font-weight: 700;">예시)</strong><strong style="box-sizing: border-box; font-weight: 700;"><br style="box-sizing: border-box;"></strong><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic";'><strong style="box-sizing: border-box; font-weight: 700;">요즘 공간의 미니멀리즘을 나도 한 번 해볼까 했지만, 뭐 이렇게 하나하나 버리기가 아까운지.. 결국, 다 집에 쟁여놓고 살아요.&nbsp;</strong></span></span></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic";'><strong style="box-sizing: border-box; font-weight: 700;">그래도 뭔가 박물관 같은 느낌이 들어서 그런지 안정적인 분위기가 물씬 나는 격하게 아끼는 공간입니다.</strong></span></span></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic"; color: rgb(124, 112, 107);'><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic";'><strong style="box-sizing: border-box; font-weight: 700;">오후 3시쯤 되면 햇빛이 샛노란 색깔로 예쁘게 거실로 들어와요.&nbsp;</strong></span></span></span></span></span>
	<br style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; color: rgb(124, 112, 107);"><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic"; color: rgb(124, 112, 107);'><span style='box-sizing: border-box; font-size: 14px; font-family: "Nanum Gothic";'><strong style="box-sizing: border-box; font-weight: 700;">요 때 여행에 대한 수다를 나누면 분위기가 두근두근할 것 같네요 :)</strong></span></span></span></span></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style="box-sizing: border-box; font-size: 14px;"><span style='box-sizing: border-box; font-family: "Nanum Barun Gothic";'><span style="box-sizing: border-box; background-color: rgb(250, 197, 28);">사진을 넣어주세요(1~2장)</span>.&nbsp;<em style="box-sizing: border-box;">&quot; 글과 관련된 공간 사진을 넣어주세요.&quot;</em></span></span></p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);">
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial; color: rgb(65, 65, 65); font-family: sans-serif; font-size: 14px; background-color: rgb(255, 255, 255);"><strong style="box-sizing: border-box; font-weight: 700;"><span style="box-sizing: border-box; color: rgb(0, 0, 0); font-size: 14px;">**필수 질문 : 마무리 멘트를 적어주세요 :)</span></strong></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'><span style='box-sizing: border-box; font-size: 14px; color: rgb(124, 112, 107); font-family: "Nanum Gothic";'><strong style="box-sizing: border-box; font-weight: 700;">예시) 그리고 알음알음 모았던 여행책은 거실 한쪽에 있는 책장에 모아두었어요. 오셔서 마구마구 꺼내 보셔도 됩니다^^. 그럼, 모임 날 봬요!</strong></span></p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br style="box-sizing: border-box;">
</p>

<p>
	<br>
</p>

<p style='box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(33, 37, 41); font-family: "Noto Sans KR", Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;'>
	<br>
</p>
`;
